// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from protocol.proto</summary>
public static partial class ProtocolReflection {

  #region Descriptor
  /// <summary>File descriptor for protocol.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtocolReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5wcm90b2NvbC5wcm90byJtCgpQMF9SZXF1ZXN0EhAKCGRldmljZUlkGAEg",
          "AigJEhYKDmRldmljZVBsYXRmb3JtGAIgAigJEhIKCmRldmljZU5hbWUYAyAC",
          "KAkSEwoLYWNjZXNzdG9rZW4YBCABKAkSDAoEbWFzaxgFIAIoCSJMCgtQMF9S",
          "ZXNwb25zZRIZCgZyZXN1bHQYASACKAsyCS5QQlJlc3VsdBIRCglhdXRoVG9r",
          "ZW4YAiABKAkSDwoHYXV0aEtleRgDIAEoCSIvCgpQMV9SZXF1ZXN0EhMKC2Fj",
          "Y2Vzc3Rva2VuGAEgAigJEgwKBG1hc2sYAiACKAkiTAoLUDFfUmVzcG9uc2US",
          "GQoGcmVzdWx0GAEgASgLMgkuUEJSZXN1bHQSEQoJYXV0aFRva2VuGAIgASgJ",
          "Eg8KB2F1dGhLZXkYAyABKAkiLQoKUDJfUmVxdWVzdBIRCglhdXRoVG9rZW4Y",
          "ASACKAkSDAoEbWFzaxgCIAEoCSKEAQoLUDJfUmVzcG9uc2USGQoGcmVzdWx0",
          "GAEgASgLMgkuUEJSZXN1bHQSEAoIcGxheWVySWQYAiABKAMSEwoLc2Vzc2lv",
          "bl9rZXkYAyABKAkSEgoKc2VydmVyVGltZRgEIAEoAxIfChdpc1BsYXRmb3Jt",
          "U2VydmljZUxpbmtlZBgFIAEoCCJDCgtQM19SZXNwb25zZRIZCgZyZXN1bHQY",
          "ASABKAsyCS5QQlJlc3VsdBIZCgZwbGF5ZXIYAiABKAsyCS5QQlBsYXllciIm",
          "CghQQlJlc3VsdBIMCgRjb2RlGAEgASgFEgwKBGRlc2MYAiABKAkiswEKCFBC",
          "UGxheWVyEhAKCHBsYXllcklkGAEgASgDEhAKCG5pY2tuYW1lGAIgASgJEgwK",
          "BHJhbmsYAyABKAUSDwoHcmVnVGltZRgEIAEoAxISCgpsb2dvdXRUaW1lGAUg",
          "ASgDEg8KB2RpYW1vbmQYBiABKAUSDAoEZ29sZBgHIAEoBRINCgVwb3dlchgI",
          "IAEoBRIPCgdwb3dlckF0GAkgASgDEhEKCWZpZ2h0RmlzaBgKIAEoBSphCglN",
          "ZXNzYWdlSWQSDwoLTUlEX1NUQVJUVVAQABIbChdNSURfTE9HSU5fV0lUSF9Q",
          "TEFURk9STRABEg0KCU1JRF9MT0dJThACEhcKE01JRF9HRVRfUExBWUVSX0lO",
          "Rk8QAyptCgpTdGF0dXNDb2RlEgYKAk9LEAASCgoGRkFJTEVEEAESEwoPU0lH",
          "TkFUVVJFX0VSUk9SEAISFwoTS0lDS19PVVRfTE9HSU5fVVNFUhADEgsKB0NB",
          "VVRJT04QBBIQCgxDTElFTlRfRVJST1IQBUIwCiBjb20uY2hhby5maXNoLnNl",
          "cnZlci5maXNoZ2FtZS5wYkIJUEJNZXNzYWdliAEA"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MessageId), typeof(global::StatusCode), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::P0_Request), global::P0_Request.Parser, new[]{ "DeviceId", "DevicePlatform", "DeviceName", "Accesstoken", "Mask" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::P0_Response), global::P0_Response.Parser, new[]{ "Result", "AuthToken", "AuthKey" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::P1_Request), global::P1_Request.Parser, new[]{ "Accesstoken", "Mask" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::P1_Response), global::P1_Response.Parser, new[]{ "Result", "AuthToken", "AuthKey" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::P2_Request), global::P2_Request.Parser, new[]{ "AuthToken", "Mask" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::P2_Response), global::P2_Response.Parser, new[]{ "Result", "PlayerId", "SessionKey", "ServerTime", "IsPlatformServiceLinked" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::P3_Response), global::P3_Response.Parser, new[]{ "Result", "Player" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PBResult), global::PBResult.Parser, new[]{ "Code", "Desc" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PBPlayer), global::PBPlayer.Parser, new[]{ "PlayerId", "Nickname", "Rank", "RegTime", "LogoutTime", "Diamond", "Gold", "Power", "PowerAt", "FightFish" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
///消息枚举编号
/// </summary>
public enum MessageId {
  [pbr::OriginalName("MID_STARTUP")] MidStartup = 0,
  [pbr::OriginalName("MID_LOGIN_WITH_PLATFORM")] MidLoginWithPlatform = 1,
  [pbr::OriginalName("MID_LOGIN")] MidLogin = 2,
  [pbr::OriginalName("MID_GET_PLAYER_INFO")] MidGetPlayerInfo = 3,
}

public enum StatusCode {
  [pbr::OriginalName("OK")] Ok = 0,
  [pbr::OriginalName("FAILED")] Failed = 1,
  [pbr::OriginalName("SIGNATURE_ERROR")] SignatureError = 2,
  [pbr::OriginalName("KICK_OUT_LOGIN_USER")] KickOutLoginUser = 3,
  [pbr::OriginalName("CAUTION")] Caution = 4,
  [pbr::OriginalName("CLIENT_ERROR")] ClientError = 5,
}

#endregion

#region Messages
/// <summary>
///startup 注册
/// </summary>
public sealed partial class P0_Request : pb::IMessage<P0_Request> {
  private static readonly pb::MessageParser<P0_Request> _parser = new pb::MessageParser<P0_Request>(() => new P0_Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<P0_Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P0_Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P0_Request(P0_Request other) : this() {
    deviceId_ = other.deviceId_;
    devicePlatform_ = other.devicePlatform_;
    deviceName_ = other.deviceName_;
    accesstoken_ = other.accesstoken_;
    mask_ = other.mask_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P0_Request Clone() {
    return new P0_Request(this);
  }

  /// <summary>Field number for the "deviceId" field.</summary>
  public const int DeviceIdFieldNumber = 1;
  private readonly static string DeviceIdDefaultValue = "";

  private string deviceId_;
  /// <summary>
  ///设备唯一标识ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DeviceId {
    get { return deviceId_ ?? DeviceIdDefaultValue; }
    set {
      deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "deviceId" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDeviceId {
    get { return deviceId_ != null; }
  }
  /// <summary>Clears the value of the "deviceId" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDeviceId() {
    deviceId_ = null;
  }

  /// <summary>Field number for the "devicePlatform" field.</summary>
  public const int DevicePlatformFieldNumber = 2;
  private readonly static string DevicePlatformDefaultValue = "";

  private string devicePlatform_;
  /// <summary>
  ///设备平台
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DevicePlatform {
    get { return devicePlatform_ ?? DevicePlatformDefaultValue; }
    set {
      devicePlatform_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "devicePlatform" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDevicePlatform {
    get { return devicePlatform_ != null; }
  }
  /// <summary>Clears the value of the "devicePlatform" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDevicePlatform() {
    devicePlatform_ = null;
  }

  /// <summary>Field number for the "deviceName" field.</summary>
  public const int DeviceNameFieldNumber = 3;
  private readonly static string DeviceNameDefaultValue = "";

  private string deviceName_;
  /// <summary>
  ///设备名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DeviceName {
    get { return deviceName_ ?? DeviceNameDefaultValue; }
    set {
      deviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "deviceName" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDeviceName {
    get { return deviceName_ != null; }
  }
  /// <summary>Clears the value of the "deviceName" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDeviceName() {
    deviceName_ = null;
  }

  /// <summary>Field number for the "accesstoken" field.</summary>
  public const int AccesstokenFieldNumber = 4;
  private readonly static string AccesstokenDefaultValue = "";

  private string accesstoken_;
  /// <summary>
  ///googleplay game center token
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Accesstoken {
    get { return accesstoken_ ?? AccesstokenDefaultValue; }
    set {
      accesstoken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "accesstoken" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAccesstoken {
    get { return accesstoken_ != null; }
  }
  /// <summary>Clears the value of the "accesstoken" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAccesstoken() {
    accesstoken_ = null;
  }

  /// <summary>Field number for the "mask" field.</summary>
  public const int MaskFieldNumber = 5;
  private readonly static string MaskDefaultValue = "";

  private string mask_;
  /// <summary>
  ///客户端randomkey
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Mask {
    get { return mask_ ?? MaskDefaultValue; }
    set {
      mask_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "mask" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMask {
    get { return mask_ != null; }
  }
  /// <summary>Clears the value of the "mask" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMask() {
    mask_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as P0_Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(P0_Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DeviceId != other.DeviceId) return false;
    if (DevicePlatform != other.DevicePlatform) return false;
    if (DeviceName != other.DeviceName) return false;
    if (Accesstoken != other.Accesstoken) return false;
    if (Mask != other.Mask) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasDeviceId) hash ^= DeviceId.GetHashCode();
    if (HasDevicePlatform) hash ^= DevicePlatform.GetHashCode();
    if (HasDeviceName) hash ^= DeviceName.GetHashCode();
    if (HasAccesstoken) hash ^= Accesstoken.GetHashCode();
    if (HasMask) hash ^= Mask.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasDeviceId) {
      output.WriteRawTag(10);
      output.WriteString(DeviceId);
    }
    if (HasDevicePlatform) {
      output.WriteRawTag(18);
      output.WriteString(DevicePlatform);
    }
    if (HasDeviceName) {
      output.WriteRawTag(26);
      output.WriteString(DeviceName);
    }
    if (HasAccesstoken) {
      output.WriteRawTag(34);
      output.WriteString(Accesstoken);
    }
    if (HasMask) {
      output.WriteRawTag(42);
      output.WriteString(Mask);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasDeviceId) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
    }
    if (HasDevicePlatform) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DevicePlatform);
    }
    if (HasDeviceName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceName);
    }
    if (HasAccesstoken) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Accesstoken);
    }
    if (HasMask) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mask);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(P0_Request other) {
    if (other == null) {
      return;
    }
    if (other.HasDeviceId) {
      DeviceId = other.DeviceId;
    }
    if (other.HasDevicePlatform) {
      DevicePlatform = other.DevicePlatform;
    }
    if (other.HasDeviceName) {
      DeviceName = other.DeviceName;
    }
    if (other.HasAccesstoken) {
      Accesstoken = other.Accesstoken;
    }
    if (other.HasMask) {
      Mask = other.Mask;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DeviceId = input.ReadString();
          break;
        }
        case 18: {
          DevicePlatform = input.ReadString();
          break;
        }
        case 26: {
          DeviceName = input.ReadString();
          break;
        }
        case 34: {
          Accesstoken = input.ReadString();
          break;
        }
        case 42: {
          Mask = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class P0_Response : pb::IMessage<P0_Response> {
  private static readonly pb::MessageParser<P0_Response> _parser = new pb::MessageParser<P0_Response>(() => new P0_Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<P0_Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P0_Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P0_Response(P0_Response other) : this() {
    result_ = other.result_ != null ? other.result_.Clone() : null;
    authToken_ = other.authToken_;
    authKey_ = other.authKey_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P0_Response Clone() {
    return new P0_Response(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::PBResult result_;
  /// <summary>
  ///0成功,其他失败
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PBResult Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "authToken" field.</summary>
  public const int AuthTokenFieldNumber = 2;
  private readonly static string AuthTokenDefaultValue = "";

  private string authToken_;
  /// <summary>
  ///玩家authtoken令牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AuthToken {
    get { return authToken_ ?? AuthTokenDefaultValue; }
    set {
      authToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "authToken" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAuthToken {
    get { return authToken_ != null; }
  }
  /// <summary>Clears the value of the "authToken" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAuthToken() {
    authToken_ = null;
  }

  /// <summary>Field number for the "authKey" field.</summary>
  public const int AuthKeyFieldNumber = 3;
  private readonly static string AuthKeyDefaultValue = "";

  private string authKey_;
  /// <summary>
  ///交换密钥 给login使用
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AuthKey {
    get { return authKey_ ?? AuthKeyDefaultValue; }
    set {
      authKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "authKey" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAuthKey {
    get { return authKey_ != null; }
  }
  /// <summary>Clears the value of the "authKey" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAuthKey() {
    authKey_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as P0_Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(P0_Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Result, other.Result)) return false;
    if (AuthToken != other.AuthToken) return false;
    if (AuthKey != other.AuthKey) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (result_ != null) hash ^= Result.GetHashCode();
    if (HasAuthToken) hash ^= AuthToken.GetHashCode();
    if (HasAuthKey) hash ^= AuthKey.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (result_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Result);
    }
    if (HasAuthToken) {
      output.WriteRawTag(18);
      output.WriteString(AuthToken);
    }
    if (HasAuthKey) {
      output.WriteRawTag(26);
      output.WriteString(AuthKey);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (result_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
    }
    if (HasAuthToken) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthToken);
    }
    if (HasAuthKey) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthKey);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(P0_Response other) {
    if (other == null) {
      return;
    }
    if (other.result_ != null) {
      if (result_ == null) {
        Result = new global::PBResult();
      }
      Result.MergeFrom(other.Result);
    }
    if (other.HasAuthToken) {
      AuthToken = other.AuthToken;
    }
    if (other.HasAuthKey) {
      AuthKey = other.AuthKey;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (result_ == null) {
            Result = new global::PBResult();
          }
          input.ReadMessage(Result);
          break;
        }
        case 18: {
          AuthToken = input.ReadString();
          break;
        }
        case 26: {
          AuthKey = input.ReadString();
          break;
        }
      }
    }
  }

}

/// <summary>
///第三方登录 or 恢复
/// </summary>
public sealed partial class P1_Request : pb::IMessage<P1_Request> {
  private static readonly pb::MessageParser<P1_Request> _parser = new pb::MessageParser<P1_Request>(() => new P1_Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<P1_Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P1_Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P1_Request(P1_Request other) : this() {
    accesstoken_ = other.accesstoken_;
    mask_ = other.mask_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P1_Request Clone() {
    return new P1_Request(this);
  }

  /// <summary>Field number for the "accesstoken" field.</summary>
  public const int AccesstokenFieldNumber = 1;
  private readonly static string AccesstokenDefaultValue = "";

  private string accesstoken_;
  /// <summary>
  ///googleplay game center token
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Accesstoken {
    get { return accesstoken_ ?? AccesstokenDefaultValue; }
    set {
      accesstoken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "accesstoken" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAccesstoken {
    get { return accesstoken_ != null; }
  }
  /// <summary>Clears the value of the "accesstoken" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAccesstoken() {
    accesstoken_ = null;
  }

  /// <summary>Field number for the "mask" field.</summary>
  public const int MaskFieldNumber = 2;
  private readonly static string MaskDefaultValue = "";

  private string mask_;
  /// <summary>
  ///客户端randomkey
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Mask {
    get { return mask_ ?? MaskDefaultValue; }
    set {
      mask_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "mask" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMask {
    get { return mask_ != null; }
  }
  /// <summary>Clears the value of the "mask" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMask() {
    mask_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as P1_Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(P1_Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Accesstoken != other.Accesstoken) return false;
    if (Mask != other.Mask) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasAccesstoken) hash ^= Accesstoken.GetHashCode();
    if (HasMask) hash ^= Mask.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasAccesstoken) {
      output.WriteRawTag(10);
      output.WriteString(Accesstoken);
    }
    if (HasMask) {
      output.WriteRawTag(18);
      output.WriteString(Mask);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasAccesstoken) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Accesstoken);
    }
    if (HasMask) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mask);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(P1_Request other) {
    if (other == null) {
      return;
    }
    if (other.HasAccesstoken) {
      Accesstoken = other.Accesstoken;
    }
    if (other.HasMask) {
      Mask = other.Mask;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Accesstoken = input.ReadString();
          break;
        }
        case 18: {
          Mask = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class P1_Response : pb::IMessage<P1_Response> {
  private static readonly pb::MessageParser<P1_Response> _parser = new pb::MessageParser<P1_Response>(() => new P1_Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<P1_Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P1_Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P1_Response(P1_Response other) : this() {
    result_ = other.result_ != null ? other.result_.Clone() : null;
    authToken_ = other.authToken_;
    authKey_ = other.authKey_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P1_Response Clone() {
    return new P1_Response(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::PBResult result_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PBResult Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "authToken" field.</summary>
  public const int AuthTokenFieldNumber = 2;
  private readonly static string AuthTokenDefaultValue = "";

  private string authToken_;
  /// <summary>
  ///玩家authtoken令牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AuthToken {
    get { return authToken_ ?? AuthTokenDefaultValue; }
    set {
      authToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "authToken" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAuthToken {
    get { return authToken_ != null; }
  }
  /// <summary>Clears the value of the "authToken" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAuthToken() {
    authToken_ = null;
  }

  /// <summary>Field number for the "authKey" field.</summary>
  public const int AuthKeyFieldNumber = 3;
  private readonly static string AuthKeyDefaultValue = "";

  private string authKey_;
  /// <summary>
  ///交换密钥 给login使用
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AuthKey {
    get { return authKey_ ?? AuthKeyDefaultValue; }
    set {
      authKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "authKey" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAuthKey {
    get { return authKey_ != null; }
  }
  /// <summary>Clears the value of the "authKey" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAuthKey() {
    authKey_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as P1_Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(P1_Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Result, other.Result)) return false;
    if (AuthToken != other.AuthToken) return false;
    if (AuthKey != other.AuthKey) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (result_ != null) hash ^= Result.GetHashCode();
    if (HasAuthToken) hash ^= AuthToken.GetHashCode();
    if (HasAuthKey) hash ^= AuthKey.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (result_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Result);
    }
    if (HasAuthToken) {
      output.WriteRawTag(18);
      output.WriteString(AuthToken);
    }
    if (HasAuthKey) {
      output.WriteRawTag(26);
      output.WriteString(AuthKey);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (result_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
    }
    if (HasAuthToken) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthToken);
    }
    if (HasAuthKey) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthKey);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(P1_Response other) {
    if (other == null) {
      return;
    }
    if (other.result_ != null) {
      if (result_ == null) {
        Result = new global::PBResult();
      }
      Result.MergeFrom(other.Result);
    }
    if (other.HasAuthToken) {
      AuthToken = other.AuthToken;
    }
    if (other.HasAuthKey) {
      AuthKey = other.AuthKey;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (result_ == null) {
            Result = new global::PBResult();
          }
          input.ReadMessage(Result);
          break;
        }
        case 18: {
          AuthToken = input.ReadString();
          break;
        }
        case 26: {
          AuthKey = input.ReadString();
          break;
        }
      }
    }
  }

}

/// <summary>
///登录
/// </summary>
public sealed partial class P2_Request : pb::IMessage<P2_Request> {
  private static readonly pb::MessageParser<P2_Request> _parser = new pb::MessageParser<P2_Request>(() => new P2_Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<P2_Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P2_Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P2_Request(P2_Request other) : this() {
    authToken_ = other.authToken_;
    mask_ = other.mask_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P2_Request Clone() {
    return new P2_Request(this);
  }

  /// <summary>Field number for the "authToken" field.</summary>
  public const int AuthTokenFieldNumber = 1;
  private readonly static string AuthTokenDefaultValue = "";

  private string authToken_;
  /// <summary>
  ///玩家令牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AuthToken {
    get { return authToken_ ?? AuthTokenDefaultValue; }
    set {
      authToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "authToken" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasAuthToken {
    get { return authToken_ != null; }
  }
  /// <summary>Clears the value of the "authToken" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearAuthToken() {
    authToken_ = null;
  }

  /// <summary>Field number for the "mask" field.</summary>
  public const int MaskFieldNumber = 2;
  private readonly static string MaskDefaultValue = "";

  private string mask_;
  /// <summary>
  ///客户端资源验签
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Mask {
    get { return mask_ ?? MaskDefaultValue; }
    set {
      mask_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "mask" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasMask {
    get { return mask_ != null; }
  }
  /// <summary>Clears the value of the "mask" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMask() {
    mask_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as P2_Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(P2_Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AuthToken != other.AuthToken) return false;
    if (Mask != other.Mask) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasAuthToken) hash ^= AuthToken.GetHashCode();
    if (HasMask) hash ^= Mask.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasAuthToken) {
      output.WriteRawTag(10);
      output.WriteString(AuthToken);
    }
    if (HasMask) {
      output.WriteRawTag(18);
      output.WriteString(Mask);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasAuthToken) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthToken);
    }
    if (HasMask) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mask);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(P2_Request other) {
    if (other == null) {
      return;
    }
    if (other.HasAuthToken) {
      AuthToken = other.AuthToken;
    }
    if (other.HasMask) {
      Mask = other.Mask;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          AuthToken = input.ReadString();
          break;
        }
        case 18: {
          Mask = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class P2_Response : pb::IMessage<P2_Response> {
  private static readonly pb::MessageParser<P2_Response> _parser = new pb::MessageParser<P2_Response>(() => new P2_Response());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<P2_Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P2_Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P2_Response(P2_Response other) : this() {
    _hasBits0 = other._hasBits0;
    result_ = other.result_ != null ? other.result_.Clone() : null;
    playerId_ = other.playerId_;
    sessionKey_ = other.sessionKey_;
    serverTime_ = other.serverTime_;
    isPlatformServiceLinked_ = other.isPlatformServiceLinked_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P2_Response Clone() {
    return new P2_Response(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::PBResult result_;
  /// <summary>
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PBResult Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "playerId" field.</summary>
  public const int PlayerIdFieldNumber = 2;
  private readonly static long PlayerIdDefaultValue = 0L;

  private long playerId_;
  /// <summary>
  ///玩家ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long PlayerId {
    get { if ((_hasBits0 & 1) != 0) { return playerId_; } else { return PlayerIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      playerId_ = value;
    }
  }
  /// <summary>Gets whether the "playerId" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPlayerId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "playerId" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPlayerId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "session_key" field.</summary>
  public const int SessionKeyFieldNumber = 3;
  private readonly static string SessionKeyDefaultValue = "";

  private string sessionKey_;
  /// <summary>
  ///后续加密用密钥
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string SessionKey {
    get { return sessionKey_ ?? SessionKeyDefaultValue; }
    set {
      sessionKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "session_key" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasSessionKey {
    get { return sessionKey_ != null; }
  }
  /// <summary>Clears the value of the "session_key" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearSessionKey() {
    sessionKey_ = null;
  }

  /// <summary>Field number for the "serverTime" field.</summary>
  public const int ServerTimeFieldNumber = 4;
  private readonly static long ServerTimeDefaultValue = 0L;

  private long serverTime_;
  /// <summary>
  ///服务器时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long ServerTime {
    get { if ((_hasBits0 & 2) != 0) { return serverTime_; } else { return ServerTimeDefaultValue; } }
    set {
      _hasBits0 |= 2;
      serverTime_ = value;
    }
  }
  /// <summary>Gets whether the "serverTime" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasServerTime {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "serverTime" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearServerTime() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "isPlatformServiceLinked" field.</summary>
  public const int IsPlatformServiceLinkedFieldNumber = 5;
  private readonly static bool IsPlatformServiceLinkedDefaultValue = false;

  private bool isPlatformServiceLinked_;
  /// <summary>
  ///是否关联 gs or gc
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool IsPlatformServiceLinked {
    get { if ((_hasBits0 & 4) != 0) { return isPlatformServiceLinked_; } else { return IsPlatformServiceLinkedDefaultValue; } }
    set {
      _hasBits0 |= 4;
      isPlatformServiceLinked_ = value;
    }
  }
  /// <summary>Gets whether the "isPlatformServiceLinked" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasIsPlatformServiceLinked {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "isPlatformServiceLinked" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearIsPlatformServiceLinked() {
    _hasBits0 &= ~4;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as P2_Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(P2_Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Result, other.Result)) return false;
    if (PlayerId != other.PlayerId) return false;
    if (SessionKey != other.SessionKey) return false;
    if (ServerTime != other.ServerTime) return false;
    if (IsPlatformServiceLinked != other.IsPlatformServiceLinked) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (result_ != null) hash ^= Result.GetHashCode();
    if (HasPlayerId) hash ^= PlayerId.GetHashCode();
    if (HasSessionKey) hash ^= SessionKey.GetHashCode();
    if (HasServerTime) hash ^= ServerTime.GetHashCode();
    if (HasIsPlatformServiceLinked) hash ^= IsPlatformServiceLinked.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (result_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Result);
    }
    if (HasPlayerId) {
      output.WriteRawTag(16);
      output.WriteInt64(PlayerId);
    }
    if (HasSessionKey) {
      output.WriteRawTag(26);
      output.WriteString(SessionKey);
    }
    if (HasServerTime) {
      output.WriteRawTag(32);
      output.WriteInt64(ServerTime);
    }
    if (HasIsPlatformServiceLinked) {
      output.WriteRawTag(40);
      output.WriteBool(IsPlatformServiceLinked);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (result_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
    }
    if (HasPlayerId) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
    }
    if (HasSessionKey) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionKey);
    }
    if (HasServerTime) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ServerTime);
    }
    if (HasIsPlatformServiceLinked) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(P2_Response other) {
    if (other == null) {
      return;
    }
    if (other.result_ != null) {
      if (result_ == null) {
        Result = new global::PBResult();
      }
      Result.MergeFrom(other.Result);
    }
    if (other.HasPlayerId) {
      PlayerId = other.PlayerId;
    }
    if (other.HasSessionKey) {
      SessionKey = other.SessionKey;
    }
    if (other.HasServerTime) {
      ServerTime = other.ServerTime;
    }
    if (other.HasIsPlatformServiceLinked) {
      IsPlatformServiceLinked = other.IsPlatformServiceLinked;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (result_ == null) {
            Result = new global::PBResult();
          }
          input.ReadMessage(Result);
          break;
        }
        case 16: {
          PlayerId = input.ReadInt64();
          break;
        }
        case 26: {
          SessionKey = input.ReadString();
          break;
        }
        case 32: {
          ServerTime = input.ReadInt64();
          break;
        }
        case 40: {
          IsPlatformServiceLinked = input.ReadBool();
          break;
        }
      }
    }
  }

}

public sealed partial class P3_Response : pb::IMessage<P3_Response> {
  private static readonly pb::MessageParser<P3_Response> _parser = new pb::MessageParser<P3_Response>(() => new P3_Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<P3_Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P3_Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P3_Response(P3_Response other) : this() {
    result_ = other.result_ != null ? other.result_.Clone() : null;
    player_ = other.player_ != null ? other.player_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public P3_Response Clone() {
    return new P3_Response(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private global::PBResult result_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PBResult Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "player" field.</summary>
  public const int PlayerFieldNumber = 2;
  private global::PBPlayer player_;
  /// <summary>
  ///玩家信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PBPlayer Player {
    get { return player_; }
    set {
      player_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as P3_Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(P3_Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Result, other.Result)) return false;
    if (!object.Equals(Player, other.Player)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (result_ != null) hash ^= Result.GetHashCode();
    if (player_ != null) hash ^= Player.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (result_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Result);
    }
    if (player_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Player);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (result_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
    }
    if (player_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(P3_Response other) {
    if (other == null) {
      return;
    }
    if (other.result_ != null) {
      if (result_ == null) {
        Result = new global::PBResult();
      }
      Result.MergeFrom(other.Result);
    }
    if (other.player_ != null) {
      if (player_ == null) {
        Player = new global::PBPlayer();
      }
      Player.MergeFrom(other.Player);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (result_ == null) {
            Result = new global::PBResult();
          }
          input.ReadMessage(Result);
          break;
        }
        case 18: {
          if (player_ == null) {
            Player = new global::PBPlayer();
          }
          input.ReadMessage(Player);
          break;
        }
      }
    }
  }

}

/// <summary>
///PB结果
/// </summary>
public sealed partial class PBResult : pb::IMessage<PBResult> {
  private static readonly pb::MessageParser<PBResult> _parser = new pb::MessageParser<PBResult>(() => new PBResult());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PBResult> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PBResult() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PBResult(PBResult other) : this() {
    _hasBits0 = other._hasBits0;
    code_ = other.code_;
    desc_ = other.desc_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PBResult Clone() {
    return new PBResult(this);
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 1;
  private readonly static int CodeDefaultValue = 0;

  private int code_;
  /// <summary>
  ///返回code
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Code {
    get { if ((_hasBits0 & 1) != 0) { return code_; } else { return CodeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      code_ = value;
    }
  }
  /// <summary>Gets whether the "code" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasCode {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "code" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearCode() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "desc" field.</summary>
  public const int DescFieldNumber = 2;
  private readonly static string DescDefaultValue = "";

  private string desc_;
  /// <summary>
  ///返回描述
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Desc {
    get { return desc_ ?? DescDefaultValue; }
    set {
      desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "desc" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDesc {
    get { return desc_ != null; }
  }
  /// <summary>Clears the value of the "desc" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDesc() {
    desc_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PBResult);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PBResult other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Code != other.Code) return false;
    if (Desc != other.Desc) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasCode) hash ^= Code.GetHashCode();
    if (HasDesc) hash ^= Desc.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasCode) {
      output.WriteRawTag(8);
      output.WriteInt32(Code);
    }
    if (HasDesc) {
      output.WriteRawTag(18);
      output.WriteString(Desc);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasCode) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
    }
    if (HasDesc) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PBResult other) {
    if (other == null) {
      return;
    }
    if (other.HasCode) {
      Code = other.Code;
    }
    if (other.HasDesc) {
      Desc = other.Desc;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Code = input.ReadInt32();
          break;
        }
        case 18: {
          Desc = input.ReadString();
          break;
        }
      }
    }
  }

}

/// <summary>
///玩家模型
/// </summary>
public sealed partial class PBPlayer : pb::IMessage<PBPlayer> {
  private static readonly pb::MessageParser<PBPlayer> _parser = new pb::MessageParser<PBPlayer>(() => new PBPlayer());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PBPlayer> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[8]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PBPlayer() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PBPlayer(PBPlayer other) : this() {
    _hasBits0 = other._hasBits0;
    playerId_ = other.playerId_;
    nickname_ = other.nickname_;
    rank_ = other.rank_;
    regTime_ = other.regTime_;
    logoutTime_ = other.logoutTime_;
    diamond_ = other.diamond_;
    gold_ = other.gold_;
    power_ = other.power_;
    powerAt_ = other.powerAt_;
    fightFish_ = other.fightFish_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PBPlayer Clone() {
    return new PBPlayer(this);
  }

  /// <summary>Field number for the "playerId" field.</summary>
  public const int PlayerIdFieldNumber = 1;
  private readonly static long PlayerIdDefaultValue = 0L;

  private long playerId_;
  /// <summary>
  ///玩家ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long PlayerId {
    get { if ((_hasBits0 & 1) != 0) { return playerId_; } else { return PlayerIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      playerId_ = value;
    }
  }
  /// <summary>Gets whether the "playerId" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPlayerId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "playerId" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPlayerId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "nickname" field.</summary>
  public const int NicknameFieldNumber = 2;
  private readonly static string NicknameDefaultValue = "";

  private string nickname_;
  /// <summary>
  ///名字
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Nickname {
    get { return nickname_ ?? NicknameDefaultValue; }
    set {
      nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "nickname" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasNickname {
    get { return nickname_ != null; }
  }
  /// <summary>Clears the value of the "nickname" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearNickname() {
    nickname_ = null;
  }

  /// <summary>Field number for the "rank" field.</summary>
  public const int RankFieldNumber = 3;
  private readonly static int RankDefaultValue = 0;

  private int rank_;
  /// <summary>
  ///段位
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Rank {
    get { if ((_hasBits0 & 2) != 0) { return rank_; } else { return RankDefaultValue; } }
    set {
      _hasBits0 |= 2;
      rank_ = value;
    }
  }
  /// <summary>Gets whether the "rank" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRank {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "rank" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRank() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "regTime" field.</summary>
  public const int RegTimeFieldNumber = 4;
  private readonly static long RegTimeDefaultValue = 0L;

  private long regTime_;
  /// <summary>
  ///注册时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long RegTime {
    get { if ((_hasBits0 & 4) != 0) { return regTime_; } else { return RegTimeDefaultValue; } }
    set {
      _hasBits0 |= 4;
      regTime_ = value;
    }
  }
  /// <summary>Gets whether the "regTime" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasRegTime {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "regTime" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearRegTime() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "logoutTime" field.</summary>
  public const int LogoutTimeFieldNumber = 5;
  private readonly static long LogoutTimeDefaultValue = 0L;

  private long logoutTime_;
  /// <summary>
  ///上次登出时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long LogoutTime {
    get { if ((_hasBits0 & 8) != 0) { return logoutTime_; } else { return LogoutTimeDefaultValue; } }
    set {
      _hasBits0 |= 8;
      logoutTime_ = value;
    }
  }
  /// <summary>Gets whether the "logoutTime" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasLogoutTime {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "logoutTime" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearLogoutTime() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "diamond" field.</summary>
  public const int DiamondFieldNumber = 6;
  private readonly static int DiamondDefaultValue = 0;

  private int diamond_;
  /// <summary>
  ///钻石
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Diamond {
    get { if ((_hasBits0 & 16) != 0) { return diamond_; } else { return DiamondDefaultValue; } }
    set {
      _hasBits0 |= 16;
      diamond_ = value;
    }
  }
  /// <summary>Gets whether the "diamond" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasDiamond {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "diamond" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearDiamond() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "gold" field.</summary>
  public const int GoldFieldNumber = 7;
  private readonly static int GoldDefaultValue = 0;

  private int gold_;
  /// <summary>
  ///金币
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Gold {
    get { if ((_hasBits0 & 32) != 0) { return gold_; } else { return GoldDefaultValue; } }
    set {
      _hasBits0 |= 32;
      gold_ = value;
    }
  }
  /// <summary>Gets whether the "gold" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasGold {
    get { return (_hasBits0 & 32) != 0; }
  }
  /// <summary>Clears the value of the "gold" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearGold() {
    _hasBits0 &= ~32;
  }

  /// <summary>Field number for the "power" field.</summary>
  public const int PowerFieldNumber = 8;
  private readonly static int PowerDefaultValue = 0;

  private int power_;
  /// <summary>
  ///体力
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Power {
    get { if ((_hasBits0 & 64) != 0) { return power_; } else { return PowerDefaultValue; } }
    set {
      _hasBits0 |= 64;
      power_ = value;
    }
  }
  /// <summary>Gets whether the "power" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPower {
    get { return (_hasBits0 & 64) != 0; }
  }
  /// <summary>Clears the value of the "power" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPower() {
    _hasBits0 &= ~64;
  }

  /// <summary>Field number for the "powerAt" field.</summary>
  public const int PowerAtFieldNumber = 9;
  private readonly static long PowerAtDefaultValue = 0L;

  private long powerAt_;
  /// <summary>
  ///体力时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long PowerAt {
    get { if ((_hasBits0 & 128) != 0) { return powerAt_; } else { return PowerAtDefaultValue; } }
    set {
      _hasBits0 |= 128;
      powerAt_ = value;
    }
  }
  /// <summary>Gets whether the "powerAt" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasPowerAt {
    get { return (_hasBits0 & 128) != 0; }
  }
  /// <summary>Clears the value of the "powerAt" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearPowerAt() {
    _hasBits0 &= ~128;
  }

  /// <summary>Field number for the "fightFish" field.</summary>
  public const int FightFishFieldNumber = 10;
  private readonly static int FightFishDefaultValue = 0;

  private int fightFish_;
  /// <summary>
  ///出战鱼
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int FightFish {
    get { if ((_hasBits0 & 256) != 0) { return fightFish_; } else { return FightFishDefaultValue; } }
    set {
      _hasBits0 |= 256;
      fightFish_ = value;
    }
  }
  /// <summary>Gets whether the "fightFish" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool HasFightFish {
    get { return (_hasBits0 & 256) != 0; }
  }
  /// <summary>Clears the value of the "fightFish" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearFightFish() {
    _hasBits0 &= ~256;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PBPlayer);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PBPlayer other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerId != other.PlayerId) return false;
    if (Nickname != other.Nickname) return false;
    if (Rank != other.Rank) return false;
    if (RegTime != other.RegTime) return false;
    if (LogoutTime != other.LogoutTime) return false;
    if (Diamond != other.Diamond) return false;
    if (Gold != other.Gold) return false;
    if (Power != other.Power) return false;
    if (PowerAt != other.PowerAt) return false;
    if (FightFish != other.FightFish) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HasPlayerId) hash ^= PlayerId.GetHashCode();
    if (HasNickname) hash ^= Nickname.GetHashCode();
    if (HasRank) hash ^= Rank.GetHashCode();
    if (HasRegTime) hash ^= RegTime.GetHashCode();
    if (HasLogoutTime) hash ^= LogoutTime.GetHashCode();
    if (HasDiamond) hash ^= Diamond.GetHashCode();
    if (HasGold) hash ^= Gold.GetHashCode();
    if (HasPower) hash ^= Power.GetHashCode();
    if (HasPowerAt) hash ^= PowerAt.GetHashCode();
    if (HasFightFish) hash ^= FightFish.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HasPlayerId) {
      output.WriteRawTag(8);
      output.WriteInt64(PlayerId);
    }
    if (HasNickname) {
      output.WriteRawTag(18);
      output.WriteString(Nickname);
    }
    if (HasRank) {
      output.WriteRawTag(24);
      output.WriteInt32(Rank);
    }
    if (HasRegTime) {
      output.WriteRawTag(32);
      output.WriteInt64(RegTime);
    }
    if (HasLogoutTime) {
      output.WriteRawTag(40);
      output.WriteInt64(LogoutTime);
    }
    if (HasDiamond) {
      output.WriteRawTag(48);
      output.WriteInt32(Diamond);
    }
    if (HasGold) {
      output.WriteRawTag(56);
      output.WriteInt32(Gold);
    }
    if (HasPower) {
      output.WriteRawTag(64);
      output.WriteInt32(Power);
    }
    if (HasPowerAt) {
      output.WriteRawTag(72);
      output.WriteInt64(PowerAt);
    }
    if (HasFightFish) {
      output.WriteRawTag(80);
      output.WriteInt32(FightFish);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HasPlayerId) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
    }
    if (HasNickname) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
    }
    if (HasRank) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rank);
    }
    if (HasRegTime) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(RegTime);
    }
    if (HasLogoutTime) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(LogoutTime);
    }
    if (HasDiamond) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Diamond);
    }
    if (HasGold) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
    }
    if (HasPower) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Power);
    }
    if (HasPowerAt) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(PowerAt);
    }
    if (HasFightFish) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(FightFish);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PBPlayer other) {
    if (other == null) {
      return;
    }
    if (other.HasPlayerId) {
      PlayerId = other.PlayerId;
    }
    if (other.HasNickname) {
      Nickname = other.Nickname;
    }
    if (other.HasRank) {
      Rank = other.Rank;
    }
    if (other.HasRegTime) {
      RegTime = other.RegTime;
    }
    if (other.HasLogoutTime) {
      LogoutTime = other.LogoutTime;
    }
    if (other.HasDiamond) {
      Diamond = other.Diamond;
    }
    if (other.HasGold) {
      Gold = other.Gold;
    }
    if (other.HasPower) {
      Power = other.Power;
    }
    if (other.HasPowerAt) {
      PowerAt = other.PowerAt;
    }
    if (other.HasFightFish) {
      FightFish = other.FightFish;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlayerId = input.ReadInt64();
          break;
        }
        case 18: {
          Nickname = input.ReadString();
          break;
        }
        case 24: {
          Rank = input.ReadInt32();
          break;
        }
        case 32: {
          RegTime = input.ReadInt64();
          break;
        }
        case 40: {
          LogoutTime = input.ReadInt64();
          break;
        }
        case 48: {
          Diamond = input.ReadInt32();
          break;
        }
        case 56: {
          Gold = input.ReadInt32();
          break;
        }
        case 64: {
          Power = input.ReadInt32();
          break;
        }
        case 72: {
          PowerAt = input.ReadInt64();
          break;
        }
        case 80: {
          FightFish = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
